import { Link, useNavigate } from '@tanstack/react-router';
import { useQueryClient } from '@tanstack/react-query';
import { BarChart3, LayoutDashboard, ListFilter, Tags, ChartNoAxesCombined, ChevronDown, LogOut, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { useFinance } from '@/lib/finance-context';
import { ProfileDialog } from './profile-dialog';
const links=[{to:'/dashboard',label:'Dashboard',icon:LayoutDashboard},{to:'/transactions',label:'Lançamentos',icon:ListFilter},{to:'/categories',label:'Categorias',icon:Tags},{to:'/reports',label:'Análises',icon:ChartNoAxesCombined}] as const;
export function FinanceShell({children}:{children:React.ReactNode}) { const {profile,user,error,loading,refresh}=useFinance(); const [menu,setMenu]=useState(false),[edit,setEdit]=useState(false); const navigate=useNavigate(),queryClient=useQueryClient();
 async function signout(){await queryClient.cancelQueries();queryClient.clear();await supabase.auth.signOut();navigate({to:'/auth',replace:true})}
 return <div className="min-h-dvh bg-background"><header className="sticky top-0 z-30 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-x-8 px-4 py-3 lg:px-8"><Link to="/dashboard" className="flex shrink-0 items-center gap-2 text-lg font-bold text-foreground"><span className="flex size-9 items-center justify-center rounded-md bg-primary text-primary-foreground"><BarChart3 size={19}/></span>Orçamento <span className="rounded bg-primary/15 px-1.5 py-0.5 text-[10px] font-extrabold text-primary">PRO</span></Link><nav className="order-3 flex w-full gap-1 overflow-x-auto pt-3 lg:order-2 lg:w-auto lg:flex-1 lg:pt-0">{links.map(({to,label,icon:Icon})=><Link key={to} to={to} activeProps={{className:'nav-active'}} className="nav-link flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"><Icon size={16}/>{label}</Link>)}</nav><div className="relative ml-auto order-2 lg:order-3"><Button variant="ghost" onClick={()=>setMenu(!menu)} className="gap-2"><span className="flex size-7 items-center justify-center rounded-full bg-primary text-xs text-primary-foreground">{(profile?.full_name||user.email||'U')[0]?.toUpperCase()}</span><span className="hidden max-w-32 truncate sm:inline">{profile?.full_name||user.email}</span><ChevronDown size={14}/></Button>{menu&&<div className="absolute right-0 top-11 z-40 w-52 rounded-md border border-border bg-card p-1 shadow-xl"><Button variant="ghost" className="w-full justify-start" onClick={()=>{setEdit(true);setMenu(false)}}><UserRound/>Editar meu perfil</Button><Button variant="ghost" className="w-full justify-start" onClick={signout}><LogOut/>Sair da conta</Button></div>}</div></div></header><main className="mx-auto max-w-7xl px-4 py-8 lg:px-8">{error&&<div className="mb-5 flex items-center justify-between rounded-md border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">{error}<Button variant="outline" onClick={()=>void refresh()}>Tentar novamente</Button></div>}{loading?<div className="py-24 text-center text-muted-foreground">Carregando seu orçamento...</div>:children}</main><ProfileDialog open={edit} onOpenChange={setEdit}/></div>
}
