import { useState, useEffect } from 'react';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';
import { useFinance } from '@/lib/finance-context';
export function ProfileDialog({open,onOpenChange}:{open:boolean;onOpenChange:(o:boolean)=>void}) {const {user,profile,refresh}=useFinance();const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[current,setCurrent]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(open){setName(profile?.full_name||'');setUsername(profile?.username||'');setPassword('');setCurrent('');setConfirm('');setError('')}},[open,profile]);
 async function save(e:React.FormEvent){e.preventDefault();if(password&&password!==confirm){setError('As senhas não coincidem.');return}setBusy(true);setError('');const {error:p}=await supabase.from('profiles').upsert({id:user.id,full_name:name.trim(),username:username.trim()});if(p){setError(p.message);setBusy(false);return}if(password){const {error:a}=await supabase.auth.updateUser({password,current_password:current});if(a){setError(a.message);setBusy(false);return}}await refresh();setBusy(false);onOpenChange(false)}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-md bg-card"><DialogHeader><DialogTitle>Editar meu perfil</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-4"><div><Label>Nome completo</Label><Input required value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Usuário</Label><Input required value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="border-t border-border pt-4"><Label>Senha atual</Label><Input type="password" value={current} onChange={e=>setCurrent(e.target.value)} required={!!password}/></div><div><Label>Nova senha (opcional)</Label><Input type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)}/></div><div><Label>Confirmar nova senha</Label><Input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></div>{error&&<p className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button disabled={busy}>{busy?'Salvando...':'Salvar'}</Button></div></form></DialogContent></Dialog>}
