import { useState } from 'react';
import { Pencil,Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/integrations/supabase/client';
import { useFinance } from '@/lib/finance-context';
import {dateBR,labels,money,months,type Transaction} from '@/lib/finance';
import { TransactionDialog } from './transaction-dialog';
export function TransactionTable({rows,compact=false}:{rows:Transaction[];compact?:boolean}){const {user,refresh}=useFinance();const [edit,setEdit]=useState<Transaction|null>(null),[del,setDel]=useState<Transaction|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function remove(){if(!del)return;setBusy(true);setError('');const {error}=await supabase.from('transactions').delete().eq('id',del.id).eq('user_id',user.id);if(error)setError(error.message);else{await refresh();setDel(null)}setBusy(false)}return <><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">Data</th>{!compact&&<th className="px-4 py-3 font-medium">Mês</th>}<th className="px-4 py-3 font-medium">Descrição</th><th className="px-4 py-3 font-medium">Categoria</th><th className="px-4 py-3 font-medium">Tipo</th><th className="px-4 py-3 text-right font-medium">Valor</th><th className="px-4 py-3 text-right font-medium">Ações</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-b border-border/60 last:border-0 hover:bg-accent/40"><td className="whitespace-nowrap px-4 py-4 text-muted-foreground">{dateBR(t.transaction_date)}</td>{!compact&&<td className="px-4 py-4 text-muted-foreground">{months[t.reference_month-1]}</td>}<td className="px-4 py-4 font-medium">{t.description}</td><td className="px-4 py-4 text-muted-foreground">{t.category}</td><td className="px-4 py-4"><span className={`type-tag type-${t.type}`}>{labels[t.type]}</span></td><td className="whitespace-nowrap px-4 py-4 text-right font-semibold">{money(Number(t.amount))}</td><td className="px-4 py-4 text-right"><div className="flex justify-end gap-1"><Button title="Editar" aria-label="Editar" variant="ghost" size="icon" onClick={()=>setEdit(t)}><Pencil/></Button><Button title="Excluir" aria-label="Excluir" variant="ghost" size="icon" onClick={()=>setDel(t)}><Trash2/></Button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="p-10 text-center text-sm text-muted-foreground">Nenhum lançamento encontrado.</div>}</div><TransactionDialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null)}} transaction={edit}/><Dialog open={!!del} onOpenChange={v=>{if(!v)setDel(null)}}><DialogContent className="bg-card"><DialogHeader><DialogTitle>Excluir lançamento?</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Esta ação não pode ser desfeita. {del?.description}</p>{error&&<p className="text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setDel(null)}>Cancelar</Button><Button variant="destructive" disabled={busy} onClick={remove}>Excluir</Button></div></DialogContent></Dialog></>}
