import { useEffect,useState } from 'react';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';
import { useFinance } from '@/lib/finance-context';
import { kinds,labels,months,type Kind,type Transaction } from '@/lib/finance';
export function TransactionDialog({open,onOpenChange,transaction,defaultMonth}:{open:boolean;onOpenChange:(o:boolean)=>void;transaction?:Transaction|null;defaultMonth?:number|undefined}){const {user,categories,refresh}=useFinance();const [description,setDescription]=useState(''),[type,setType]=useState<Kind>('receita'),[category,setCategory]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[month,setMonth]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!open)return;const now=new Date();const chosenMonth=transaction?.reference_month||defaultMonth||now.getMonth()+1;const currentDay=String(Math.min(now.getDate(),new Date(now.getFullYear(),chosenMonth,0).getDate())).padStart(2,'0');const today=`${now.getFullYear()}-${String(chosenMonth).padStart(2,'0')}-${currentDay}`;setDescription(transaction?.description||'');setType(transaction?.type||'receita');setCategory(transaction?.category||'');setAmount(transaction?String(transaction.amount):'');setDate(transaction?.transaction_date||today);setMonth(chosenMonth);setError('')},[open,transaction,defaultMonth]);
 function changeDate(value:string){setDate(value);if(value)setMonth(Number(value.slice(5,7)))}function changeMonth(value:number){setMonth(value);if(date){const [year,,day]=date.split('-').map(Number);const y=year??new Date().getFullYear(),d=day??1;const last=new Date(y,value,0).getDate();setDate(`${y}-${String(value).padStart(2,'0')}-${String(Math.min(d,last)).padStart(2,'0')}`)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const payload={user_id:user.id,description:description.trim(),type,category,amount:Number(amount),transaction_date:date,reference_month:month,reference_year:Number(date.slice(0,4)),paid:transaction?.paid||false};const result=transaction?await supabase.from('transactions').update(payload).eq('id',transaction.id).eq('user_id',user.id):await supabase.from('transactions').insert(payload);if(result.error)setError(result.error.message);else{await refresh();onOpenChange(false)}setBusy(false)}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[95dvh] max-w-lg overflow-y-auto bg-card"><DialogHeader><DialogTitle>{transaction?'Editar Lançamento':'Novo Lançamento'}</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={save}><div className="sm:col-span-2"><Label>Descrição</Label><Input required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Salário mensal"/></div><div><Label>Tipo</Label><select className="field" value={type} onChange={e=>{setType(e.target.value as Kind);setCategory('')}}>{kinds.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></div><div><Label>Categoria</Label><select className="field" required value={category} onChange={e=>setCategory(e.target.value)}><option value="">Selecione</option>{categories.filter(c=>c.type===type).map(c=><option key={c.id}>{c.name}</option>)}{transaction?.category&&!categories.some(c=>c.name===transaction.category&&c.type===type)&&<option>{transaction.category}</option>}</select></div><div><Label>Valor (R$)</Label><Input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><Label>Data</Label><Input type="date" required value={date} onChange={e=>changeDate(e.target.value)}/></div><div className="sm:col-span-2"><Label>Mês de referência</Label><select className="field" value={month} onChange={e=>changeMonth(Number(e.target.value))}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></div>{error&&<p className="text-sm text-destructive sm:col-span-2">{error}</p>}<div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button disabled={busy}>{busy?'Salvando...':'Salvar'}</Button></div></form></DialogContent></Dialog>}
